### PR TITLE
Remove unused explicit template instantiation and fix CUDA compilation

### LINKED ISSUE #375: Remove unused explicit template instantiation

### PR DESCRIPTION
**Pull request by icui**
# Issue Number

Closes #375

### CODE REVIEW

**Review by lsawade — APPROVED** [review]
LGTM

File: src/IO/HDF5/native_type.cpp [hunk 1]
```diff
@@ -3,31 +3,3 @@
 #include "H5Cpp.h"
 #endif
 #include "IO/HDF5/impl/native_type.tpp"
```
Comment (Rohit-Kakodkar) [inline src/IO/HDF5/native_type.cpp:5]: Do we still need this file?

**Review by Rohit-Kakodkar — COMMENTED** [review]
Do we still need any of the .cpp without the instantiations

**Review by Rohit-Kakodkar — APPROVED** [review]
This LGTM. Thanks for fixing the compilation

**Review by lsawade — APPROVED** [review]
Sweet!
